# Generated by Django 5.1.5 on 2025-01-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
